name: check_code_quality

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install
      run: pip install -r requirements.txt
    - run: |
        python -m pip install --upgrade pip
        pip install black
    - run: |
        black --check --verbose